# Generated by Django 4.2.21 on 2025-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
