# Generated by Django 4.2.21 on 2025-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_neighborhood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
