# Generated by Django 4.2.21 on 2025-06-05 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_stores", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
