# Generated by Django 4.2.21 on 2025-06-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseDrink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("alcohol_percentage", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteDrink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RawDrink",
            fields=[
                (
                    "basedrink_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="drink.basedrink",
                    ),
                ),
                ("store_name", models.CharField(max_length=50)),
            ],
            bases=("drink.basedrink",),
        ),
        migrations.CreateModel(
            name="StoreDrink",
            fields=[
                (
                    "basedrink_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="drink.basedrink",
                    ),
                ),
                ("price", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
            bases=("drink.basedrink",),
        ),
    ]
