# Generated by Django 4.2.21 on 2025-06-05 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drink", "0001_initial"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritedrink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="basedrink",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_ingredients", to="drink.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="storedrink",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.store"
            ),
        ),
        migrations.AddField(
            model_name="favoritedrink",
            name="raw_drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drink.rawdrink",
            ),
        ),
        migrations.AddField(
            model_name="favoritedrink",
            name="store_drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drink.storedrink",
            ),
        ),
    ]
