# Generated by Django 4.2.21 on 2025-05-22 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('drinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritedrink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basedrink',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_ingredients', to='drinks.ingredient'),
        ),
        migrations.AddField(
            model_name='storedrink',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='favoritedrink',
            name='raw_drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.rawdrink'),
        ),
        migrations.AddField(
            model_name='favoritedrink',
            name='store_drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.storedrink'),
        ),
    ]
