# Generated by Django 4.2.21 on 2025-07-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="user2",
            new_name="followed",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="user1",
            new_name="follower",
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("follower", "followed")},
        ),
    ]
