# Generated by Django 4.2.21 on 2025-07-16 18:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_user2_contact_followed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
